spring.application.name=LaFachada
server.port=${SERVER_PORT:8086}
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.output.ansi.enabled=always
spring.data.web.pageable.serialization-mode=via-dto
spring.jackson.serialization.fail-on-empty-beans=false