spring.application.name=LaFachada
server.port=8086

spring.datasource.platform=mariadb
spring.datasource.url=jdbc:mariadb://localhost:3306/publicacion_test?createDatabaseIfNotExist=true
spring.datasource.username=public_user_test
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.output.ansi.enabled=always


