spring.application.name=publicacion-service
server.port=8086

# CONEXIÓN DIRECTA A TU MARIADB DE DOCKER (PUERTO 3308)
spring.datasource.url=jdbc:mariadb://db:3308/publicacion_test?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# CONFIGURACIÓN DE HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# LOGS Y SERIALIZACIÓN
# Habilita colores en la consola para una mejor legibilidad
spring.output.ansi.enabled=always
spring.data.web.pageable.serialization-mode=via-dto
spring.jackson.serialization.fail-on-empty-beans=false